skipped_columns = [
    "access", "amenities", "availability_30", "availability_365",
    "availability_60", "availability_90", "calculated_host_listings_count",
    "calculated_host_listings_count_entire_homes",
    "calculated_host_listings_count_private_rooms",
    "calculated_host_listings_count_shared_rooms",
    "calendar_last_scraped", "calendar_updated", "cancellation_policy",
    "city", "cleaning_fee", "country", "country_code", "description",
    "experiences_offered", "extra_people", "guests_included",
    "has_availability", "host_about", "host_acceptance_rate",
    "host_has_profile_pic", "host_identity_verified", "host_is_superhost",
    "host_listings_count", "host_location", "host_name", "host_neighbourhood",
    "host_picture_url", "host_response_rate", "host_response_time",
    "host_since", "host_thumbnail_url", "host_total_listings_count",
    "host_url", "host_verifications", "house_rules", "instant_bookable",
    "interaction", "is_business_travel_ready",
    "jurisdiction_names", "last_scraped", "license", "listing_url",
    "market", "maximum_maximum_nights", "maximum_minimum_nights",
    "maximum_nights", "maximum_nights_avg_ntm", "medium_url",
    "minimum_maximum_nights", "minimum_minimum_nights", "minimum_nights",
    "minimum_nights_avg_ntm", "monthly_price", "name", "neighborhood_overview",
    "neighbourhood", "neighbourhood_cleansed", "notes", "number_of_reviews_ltm",
    "picture_url", "require_guest_phone_verification",
    "require_guest_profile_picture", "requires_license",
    "review_scores_accuracy", "review_scores_checkin",
    "review_scores_cleanliness", "review_scores_communication",
    "review_scores_location", "review_scores_value", "scrape_id",
    "security_deposit", "smart_location", "space", "square_feet", "state",
    "street", "summary", "thumbnail_url", "transit", "weekly_price",
    "xl_picture_url",
]
